### ISSUE TITLE
Попробовать scrapy

### ISSUE THREAD

**Issue by stleon** [demidovakatya/movies#1]
https://scrapy.org

или 

https://habrahabr.ru/post/127584/

**Comment by demidovakatya** [comment]
Спасибо!
BeautifulSoup вообще норм выбор для парсинга или есть библиотеки значительно лучше и стоит переходить на них?

**Comment by demidovakatya** [comment]
Попробовала. Имхо, синтаксис у них сложнее и менее интуитивный, чем у супа. Пока что последнего мне хватает.
